{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 .SFNSMono-Regular;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red255\green255\blue255;\red27\green31\blue34;
\red27\green31\blue34;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;\cssrgb\c100000\c100000\c100000;\cssrgb\c14118\c16078\c18039;
\cssrgb\c14118\c16078\c18039;}
\margl1440\margr1440\vieww21080\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs24 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 FROM\cf4 \strokec4  rocker/rstudio:4.1.0\
\
\cf2 \strokec2 RUN\cf4 \strokec4  apt-get update -y\\\
&& apt-get install -y dpkg-dev zlib1g-dev libssl-dev libffi-dev zlib1g-dev libbz2-dev liblzma-dev build-essential libglpk40\\\
&& apt-get install -y curl libcurl4-openssl-dev\\\
&& apt-get install -y git\\\
&& R -e \cf2 \strokec2 "install.packages('BiocManager')"\cf4 \strokec4 \\\
&& R -e \cf2 \strokec2 "BiocManager::install('biomaRt')"\cf4 \strokec4 \\\
\pard\pardeftab720\partightenfactor0
\cf5 \outl0\strokewidth0 && R -e \cf2 "install.packages(\'91caret\'92)\'94\cf5 \\\
\cf4 \outl0\strokewidth0 \strokec4 && R -e \cf2 \strokec2 "install.packages('data.table')"\cf4 \strokec4 \\\
\pard\pardeftab720\partightenfactor0
\cf4 && R -e \cf2 \strokec2 "install.packages('ggplot2')"\cf4 \strokec4 \\\
&& R -e \cf2 \strokec2 "install.packages('synapser', repos = c('http://ran.synapse.org', 'http://cran.fhcrc.org'))"\cf4 \strokec4 \\\
&& R -e \cf2 \strokec2 "devtools::install_github('Sage-Bionetworks/knit2synapse')"\cf4 \strokec4 \\\
&& R -e \cf2 \strokec2 "install.packages('knitr')"\cf4 \strokec4 \\\
&& R -e \cf2 \strokec2 "BiocManager::install('limma')"\cf4 \strokec4 \\\
\pard\pardeftab720\partightenfactor0
\cf5 \outl0\strokewidth0 && R -e \cf2 "install.packages(\'91Matrix\'92)\'94\cf5 \\\
\pard\pardeftab720\partightenfactor0
\cf5 && R -e \cf2 "install.packages(\'91patchwork\'92)\'94\cf5 \\\cf4 \outl0\strokewidth0 \strokec4 \
\pard\pardeftab720\partightenfactor0
\cf4 && R -e \cf2 \strokec2 "install.packages('RColorBrewer')"\cf4 \strokec4 \\\
\pard\pardeftab720\partightenfactor0
\cf5 \outl0\strokewidth0 && R -e \cf2 "install.packages(\'91Seurat\'92)\'94\cf5 \\\cf4 \outl0\strokewidth0 \strokec4 \
\pard\pardeftab720\partightenfactor0
\cf4 && R -e \cf2 \strokec2 "install.packages('tidyverse')"\cf4 \strokec4 \\\
\
\
run mkdir /home/lheath/celltype_mapping \cf2 \strokec2 \\ \
\cf4 \strokec4 && git clone https://github.com/lauraheath/scRNAseq-subtype-mapping.git /home/\cf5 \outl0\strokewidth0 lheath/celltype_mapping}